config/api/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import BookAPIView

urlpatterns = []

config/books/urls.py
from django.urls import path, re_path, include
from .views import index, BookListView, BookDetailView, AuthorView, AuthorDetailView, about, contact, logout_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('books/', BookListView.as_view(), name='books-list'),
    re_path(r'^books/(?P<pk>\d+)$', BookDetailView.as_view(), name='books-detail'),
    path('', index, name='index'),
    path('authors/', AuthorView.as_view(), name='authors-list'),
    re_path(r'^authors/(?P<pk>\d+)$', AuthorDetailView.as_view(), name='authors-detail'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),

    path('accounts/logout/', logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('', include('books.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/books/models.py
from django.db import models
from django.urls import reverse


class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Введите жанр книги",
                            verbose_name="Жанр книги")

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите язык книги",
                            verbose_name="Язык книги")

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите название издательства",
                            verbose_name="Название издательства")

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100,
                                  help_text="Введите имя автора",
                                  verbose_name="Имя автора")
    last_name = models.CharField(max_length=100,
                                 help_text="Введите фамилию автора",
                                 verbose_name="Фамилия автора")
    date_of_birth = models.DateField(help_text="Введите дату рождения",
                                     verbose_name="Дата рождения",
                                     null=True, blank=True)
    about = models.TextField(help_text="Введите сведенья об авторе",
                             verbose_name="Сведенья об авторе")
    photo = models.ImageField(upload_to='images',
                              help_text="Введите дату рождения",
                              verbose_name="Дата рождения",
                              null=True, blank=True)

    def __str__(self):
        return self.last_name


class Book(models.Model):
    title = models.CharField(max_length=200,
                             help_text="Введите название книги",
                             verbose_name="Название книги")
    genre = models.ForeignKey("Genre", on_delete=models.CASCADE, null=True,
                              help_text="Выберите жанр книги",
                              verbose_name="Жанр книги")
    language = models.ForeignKey('Language', on_delete=models.CASCADE, null=True,
                                 help_text="Выберите язык книги",
                                 verbose_name="Язык книги")
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE,
                                  help_text="Выберите издатльство",
                                  verbose_name="Издатльство", null=True)
    year = models.CharField(max_length=4,
                            help_text="Введите год издания",
                            verbose_name="Год издания")
    author = models.ManyToManyField("Author",
                                    help_text="Выберите автора(ов) книги",
                                    verbose_name="Автор(ы) книги")
    summary = models.TextField(max_length=1000,
                               help_text="Введите крадкое описание книги",
                               verbose_name="Крадкое описание книги")
    isbn = models.CharField(max_length=13,
                            help_text="Должно содержать 13 символов",
                            verbose_name="ISBN книги")
    price = models.DecimalField(decimal_places=2, max_digits=7,
                                help_text="Введите цену книги",
                                verbose_name="Цена (руб.)")
    photo = models.ImageField(upload_to='images',
                              help_text="Введите изображение обложки",
                              verbose_name="Изображение обложки")

    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])

    display_author.short_description = 'Авторы'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # Возвращает URL-aдpec для доступа к определенному экземпляру книги
        return reverse('book-detail', args=[str(self.id)])


class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите статус экземпляра книги",
                            verbose_name="Статус экземпляра книги")

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    inv_nom = models.CharField(max_length=20, null=True,
                               help_text="Введите инвентарный номер книги",
                               verbose_name="Инвентарный номер")
    status = models.ForeignKey('Status', on_delete=models.CASCADE, null=True,
                               help_text="Изменить состояние экземпляра",
                               verbose_name="Состояние экземпляра книги")
    due_back = models.DateField(null=True, blank=True,
                                help_text="Введите конец срока статуса",
                                verbose_name="Дата окончания статуса")

    class Meta:
        ordering = ["due_back"]

    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book, self.status)

config/books/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Book, BookInstance, Author
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    text_head = 'На данном сайте можно пролучить книги в электронном виде'
    # Данные о книгах и их количестве
    books = Book.objects.all()
    num_books = Book.objects.all().count()
    # Данные об экземплярах книг в БД
    num_instances = BookInstance.objects.all().count()
    # Доступные книги (статус = 'На складе')
    num_instances_available = BookInstance.objects.filter(status__exact=1).count()
    # Данные об авторах книг
    authors = Author.objects
    num_authors = Author.objects.all().count()
    context = {'text_head': text_head,
               'books': books,
               'num_books': num_books,
               'num_instances': num_instances,
               'num_instances_available': num_instances_available,
               'authors': authors,
               'num_authors': num_authors,}
    return render(request, 'books/index.html', context)


class BookListView(ListView):
    model = Book
    context_object_name = 'books'
    paginate_by = 6


class BookDetailView(DetailView):
    model = Book


class AuthorView(ListView):
    model = Author
    paginate_by = 6


class AuthorDetailView(DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, ListView):
    """
    Универсальный класс представления списка книг,
    находящихся в заказе у текущего пользователя.
    """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='2').order_by('due_back')


def about(request):
    text_head = 'Сведения о компании'
    name = 'ООО "ГлаДИ"'
    rab1 = ('Разработка приложений на основе '
            'систем искусственного интеллекта')
    rab2 = 'Распознавание объектов дорожной инфраструктуры'
    rab3 = ('Создание графических АРТ-объектов на основе '
            'систем искусственного интелпекта')
    rab4 = ('Создание цифровых интерактивных книг, учебных пособий'
            ' автоматизированных обучающих систем')
    context = {'text_head': text_head, 'name': name, 'rab1': rab1, 'rab2': rab2, 'rab3': rab3, 'rab4': rab4}
    return render(request, 'books/about.html', context)


def contact(request):
    text_head = 'Контакты'
    name = 'ООО "ГлаДИ"'
    address = 'Москва, ул. Планерная, д. 20, к. 1'
    tel = '495-345-45-45'
    email = 'iis_info@mail.ru'
    context = {'text_head': text_head, 'name': name, 'address': address, 'tel': tel, 'email': email}
    return render(request, 'books/contact.html', context)


def logout_view(request):
    logout(request)
    return redirect('/')

config/books/templates/books/about.html
{% extends "books/base.html" %}
{% load static %}
{% block title %}О компании{% endblock title %}
{% block content %}
<div class="container text-start">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-custom overflow-hidden text-center bg-body-tertiary rounded-3">
      <li class="breadcrumb-item">
        <a class="link-body-emphasis fw-semibold text-decoration-none" href="/">
          Главная
        </a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        О компании
      </li>
    </ol>
  </nav>
</div>

<div class="row text-center text-dark lh-2 my-4">
    <h1>{{ text_head }}</h1>
    <h3>{{ name }}</h3>
</div>

<div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-label="Slide 1" aria-current="true"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class=""></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class=""></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="3" aria-label="Slide 4" class=""></button>
    </div>
    <div class="carousel-inner bg-dark-subtle">
      <div class="carousel-item active">
        <img src="{% static 'images/image2.jpg' %}" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true">
        <div class="container">
          <div class="carousel-caption text-start">
            <h1 class="opacity-75 shadow-lg bg-body rounded text-black">Компьютерное зрение</h1>
            <p class="opacity-75 shadow-lg p-3  bg-body rounded text-black">{{ rab2 }}</p>
            <p><a class="btn btn-lg btn-primary" href="#">Увидеть</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/image4.jpg' %}" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true">
        <div class="container">
          <div class="carousel-caption">
            <h1 class="opacity-75 shadow-lg bg-body rounded text-black">Арт-объекты</h1>
            <p class="opacity-75 shadow-lg p-3  bg-body rounded text-black">{{ rab3 }}</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/image3.jpg' %}" class="bd-placeholder-img" width="100%" height="730" aria-hidden="true">
        <div class="container">
          <div class="carousel-caption text-end">
            <h1 class="opacity-75 shadow-lg bg-body rounded text-black">Электронные книги</h1>
            <p class="opacity-75 shadow-lg p-3  bg-body rounded text-black">{{ rab4 }}</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/image1.jpg' %}" class="bd-placeholder-img" width="100%" height="730" aria-hidden="true">
        <div class="container">
          <div class="carousel-caption text-end">
            <h1 class="opacity-75 shadow-lg bg-body rounded text-black">Искусственный интеллект</h1>
            <p class="opacity-75 shadow-lg p-3  bg-body rounded text-black">{{ rab1 }}</p>
            <p><a class="btn btn-lg btn-primary" href="#">Подумать</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

{% endblock content %}
{% block books %}{% endblock books %}

config/books/templates/books/author_detail.html
{% extends "books/base.html" %}
{% load static %}
{% block title %}{{ author.last_name }} {{ author.first_name }}{% endblock title %}
{% block style %}
    <style>
        .footer {
            position: absolute;
            left: 0;
            bottom: 0;
            width: 100%;
            height: 114px;
        }
    </style>
{% endblock style %}
{% block content %}
    <div class="container text-start">

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-custom overflow-hidden text-center bg-body-tertiary rounded-3">
              <li class="breadcrumb-item">
                  <a class="link-body-emphasis fw-semibold text-decoration-none" href="/">
                      Главная
                  </a>
              </li>
              <li class="breadcrumb-item active">
                  <a class="link-body-emphasis fw-semibold text-decoration-none" href="/authors/">Все авторы</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                  {{ author.last_name }} {{ author.first_name }}
              </li>
          </ol>
      </nav>
        <div class="row featurette">
            <div class="col-md-7 order-md-2">
                <h2 class="featurette-heading fw-normal lh-1">{{ author.last_name }} {{ author.first_name }}</h2><br>
                <strong class="text-muted">О писателе:</strong>
                <p class="lead text-muted"> {{ author.about }}</p>
                <p class="text-muted"><strong>Родился:</strong> {{ author.date_of_birth }}</p>
            </div>
            <div class="col-md-5 order-md-1">
                <img src="{{ author.photo.url }}" class="ms-5" alt="connect" style="max-height: 400px">
            </div>
        </div>
    </div>
{% endblock content %}
{% block books %}{% endblock books %}

config/books/templates/books/author_list.html
{% extends "books/base.html" %}
{% load static %}
{% block title %}Список авторов{% endblock title %}
{% block content %}
    <div class="container my-2">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom overflow-hidden text-center bg-body-tertiary rounded-3">
                <li class="breadcrumb-item">
                    <a class="link-body-emphasis fw-semibold text-decoration-none" href="/">
                        Главная
                    </a>
                </li>
                <li class="breadcrumb-item active">
                    Все авторы
                </li>
            </ol>
        </nav>
    </div>
    <div class="row text-center text-dark lh-2 my-4">
        <h1>Список авторов книг</h1>
    </div>
    {% if author_list %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for author in author_list.all %}
            <div class="col">
                <div class="card shadow-sm">
                    <img class="bd-placeholder-img card-img-top" width="100%" height="500" src="{{ author.photo.url }}" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"/>
                    <div class="card-body">
                        <h4>{{author.last_name}} {{author.first_name}}</h4>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a type="button" class="btn btn-sm btn-outline-secondary" href="/authors/{{ author.id }}">Смотря</a>
                            </div>
                            <small class="text-body-secondary">Дата рождения: {{ author.date_of_birth }}</small>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h1>нет ни ху а <br>:(</h1>
    {% endif %}

{% endblock content %}
{% block books %}{% endblock books %}

config/books/templates/books/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script defer src="/static/js/bootstrap.bundle.min.js"></script>
    <title>{% block title %}{% endblock title %}</title>
    {% block style %}{% endblock style %}
</head>

<body class="d-flex flex-column h-100 bg-body-tertiary">
    <header class="p-3 text-bg-dark flex-shrink-0">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                  <img src="{% static 'images/logo4.png' %}" width="50" height="50" class="m-2 my-2" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 118 94" role="img"/>
                </a>
                {% block sidebar %}
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                  <li><a href="{% url 'index' %}" class="nav-link px-2 text-white">Главная страница</a></li>
                  <li><a href="{% url 'books-list' %}" class="nav-link px-2 text-white">Все книги</a></li>
                  <li><a href="{% url 'authors-list' %}" class="nav-link px-2 text-white">Все авторы</a></li>
                  <li><a href="{% url 'about' %}" class="nav-link px-2 text-white">О компании</a></li>
                  <li><a href="{% url 'contact' %}" class="nav-link px-2 text-white">Контакты</a></li>
                </ul>
                {% endblock sidebar %}
                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                  <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Поиск..." aria-label="Поиск">
                </form>

                <div class="text-end">
                    {% if request.user.id is None %}
                        <a href="{% url 'login' %}" type="button" class="btn btn-outline-light me-2" >Войти</a>
                        <a href="{% url 'index' %}" type="button" class="btn btn-warning">Регистрация</a>
                    {% else %}
                        {{ request.user }}
                        <a href="{% url 'logout' %}" type="button" class="btn btn-outline-light me-2 ms-2" >Выйти</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            {% block content %}
            {% endblock content %}

            {% block books %}
                {% if books %}
                    <div class="album py-5 bg-body-tertiary">
                        <div class="container">
                            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                                {% for obj in books %}
                                    <div class="col">
                                        <div class="card shadow-sm">
                                            <img class="bd-placeholder-img card-img-top" width="100%" height="500" src="{{ obj.photo.url }}" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"/>
                                            <div class="card-body">
                                                <h4>{{obj.title}}</h4>
                                                <p class="card-text small">
                                                    Цена: {{obj.price}} руб.
                                                </p>
                                                <div class="d-flex justify-content-between align-items-center">
                                                    <div class="btn-group">
                                                        <a type="button" class="btn btn-sm btn-outline-secondary" href="/books/{{ obj.id }}">Смотря</a>
                                                        <a type="button" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                                                    </div>
                                                    <small class="text-body-secondary">ISBN: {{ obj.isbn }}</small>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="container my-5">
                        <div class="bg-body-tertiary p-5 rounded">
                            <div class="col-sm-8 py-5 mx-auto">
                                <h1 class="display-5 fw-normal">Нет информации о книгах</h1>
                                <p class="fs-5">На данный момент в базе данных нет информации о книгах, если вам что-то не нравится, то можете <a href="#">ничего</a> или <a href="https://www.youtube.com/watch?v=kSnrQR9BS80">чего</a></p>
                                <p>Ждите там, ну не знаю, партч, картч, фарч или что вы там ждете.</p>
                                <p>
                                  <a class="btn btn-primary" href="https://www.youtube.com/watch?v=kSnrQR9BS80" role="button">Узнать чего там »</a>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endblock books %}

            <!-- пагинатор -->
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.paginator.num_pages > 1 %}
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; Первая</a>
                            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                        {% endif %}
                        <span class="current">
                            {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{{ page_obj.next_page_number }}">Следующая</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">Предыдущая &raquo;</a>
                        {% endif %}
                    {% endif %}
                </span>
            </div>
            <!-- пагинатор -->

        </div>
    </div>
    {% block footer %}
    <footer class="footer mt-auto text-body-secondary py-5 border-top text-bg-dark">
        <div class="container text-white">
            <p class="float-end mb-1">
                <a class="text-white" href="#">Вернуться к началу</a>
            </p>

            <p>© ООО "ГлаДИ", 2024. Все права защищены</p>

        </div>
    </footer>
    {% endblock footer %}
</body>
</html>

config/books/templates/books/book_detail.html
{% extends "books/base.html" %}
{% load static %}
{% block title %}{{ book.title }}{% endblock title %}
{% block content %}
    <div class="container text-start">

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-custom overflow-hidden text-center bg-body-tertiary rounded-3">
              <li class="breadcrumb-item">
                  <a class="link-body-emphasis fw-semibold text-decoration-none" href="/">
                      Главная
                  </a>
              </li>
              <li class="breadcrumb-item active">
                  <a class="link-body-emphasis fw-semibold text-decoration-none" href="/books/">Все книги</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                  {{ book.title }}
              </li>
          </ol>
      </nav>
        <div class="row featurette">
            <div class="col-md-7 order-md-2">
                <h2 class="featurette-heading fw-normal lh-1">"{{ book.title }}"</h2><br>
                <strong class="text-muted">Аннотация:</strong>
                <p class="lead text-muted"> {{ book.summary }}</p>
                <p class="text-muted"><strong>Цена:</strong> {{ book.price }}</p>
                <p class="text-muted"><strong>Жанр:</strong> {{ book.genre }}</p>
                <p class="text-muted"><strong>ISBN:</strong> {{ book.isbn }}</p>
                <p class="text-muted"><strong>Язык:</strong> {{ book.language }}</p>
                <p class="text-muted"><strong>Издательство:</strong> {{ book.publisher }}</p>
            </div>
            <div class="col-md-5 order-md-1">
                <img src="{{ book.photo.url }}" class="ms-5" alt="connect" style="max-height: 500px">
            </div>
        </div>
        <div style="margin-left: 20px; margin-top: 10px">
            <h4>Количество экземпляров книг в БД</h4>
            {% for copy in book.bookinstance_set.all %}
            <hr>
                <p class="text-muted">
                    <strong>Инвентарный нoмep:</strong> {{ copy.id }}</p>
                <p class="text-muted">
                    <strong>Cтaтус экземпляра книги:</strong> {{ copy.status }}</p>
            </hr>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

config/books/templates/books/book_list.html
{% extends "books/base.html" %}
{% load static %}
{% block title %}Мир книг{% endblock title %}
{% block content %}

  <div class="container my-2">
      <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-custom overflow-hidden text-center bg-body-tertiary rounded-3">
              <li class="breadcrumb-item">
                  <a class="link-body-emphasis fw-semibold text-decoration-none" href="/">
                      Главная
                  </a>
              </li>
              <li class="breadcrumb-item active">
                  Все книги
              </li>
          </ol>
      </nav>
  </div>

  <div class="row text-center text-dark lh-2 my-4">
    <h1>Список книг</h1>
  </div>
{% endblock content %}

config/books/templates/books/contact.html
{% extends "books/base.html" %}
{% load static %}
{% block title %}Контакты{% endblock title %}
{% block style %}
    <style>
        .footer {
          position: absolute;
          left: 0;
          bottom: 0;
          width: 100%;
          height: 114px;
        }
    </style>
{% endblock style %}
{% block content %}
<div class="container text-start">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-custom overflow-hidden text-center bg-body-tertiary rounded-3">
      <li class="breadcrumb-item">
        <a class="link-body-emphasis fw-semibold text-decoration-none" href="/">
          Главная
        </a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        Контакты
      </li>
    </ol>
  </nav>
</div>

<div class="container-fluid">
  <div class="row my-2 text-center">
    <div class="col-5"></div>
    <div class="col-1 text-center">
      <img src="{% static 'images/image1.jpg' %}" width="140" height="140">
    </div>
    <div class="col-5"></div>
  </div>
  <div class="row my-2 text-primary text-center">
    <h3>{{ name }}</h3>
  </div>
  <div class="row my-2 text-muted">
    <h4 class="text-center">{{ text_head }}</h4>
  </div>
  <div class="col-3"></div>
  <div class="col-6">
    <table class="table table-bordered table-striped text-start">
      <thead>
        <tr>
          <th>Адрес</th>
          <th>Телефон</th>
          <th>e-mail</th>
        </tr>
      </thead>
      <tbody>
        <tr>
            <td>{{ address }}</td>
            <td>{{ tel }}</td>
            <td>{{ email }}</td>
        </tr>
      </tbody>
      </table>
  </div>
  <div class="col-3"></div>
</div>

{% endblock content %}
{% block books %}{% endblock books %}